### ISSUE TITLE
使用ssh代理连接不上

### ISSUE THREAD

**Issue by itodouble** [dromara/RedisFront#28]
版本1.0.7
使用的是从resp导出的配置文件 在resp中正常 RedisFront提示'加载超时，请重试！' 
我已经将超时时间设置为'60000'
![Snipaste_2023-04-11_10-30-25](https://user-images.githubusercontent.com/13508120/231040675-88c84e50-6223-4453-aa6e-00db3ef20955.png)
![Snipaste_2023-04-11_10-31-01](https://user-images.githubusercontent.com/13508120/231040681-e0440721-2c18-47a5-8b36-97a3297154be.png)

**Comment by jicehuvbyb29942** [comment]
我连线上redis也是, 会超时,  设置的600s过期
